### ISSUE TITLE
How can this be used in Swift

### ISSUE THREAD

**Issue by AntiMoron** [betzerra/MosaicUI#18]
as the post title.

**Comment by betzerra** [comment]
To be honest I would check https://github.com/betzerra/MosaicLayout and make a few changes. 

MosaicUI has been made 3 years ago.

**Comment by AntiMoron** [comment]
Good library should keep up with fasion .
Looking forward to it!!! :+1:

**Comment by betzerra** [comment]
Thanks a lot :-)

I may update this in the future but the interface would look more like MosaicLayout since now we have UICollectionViews :-)

But for the moment I'm focusing on updating this other personal project https://appsto.re/ar/t-P-Q.i

I wish I can do everything at the same time but I can't LOL

Thanks again for caring about this repo
